[versions]
loom = "1.12-SNAPSHOT"
preprocessor = "7de7ac9"
shadow = "7.1.2"
blossom = "1.3.1"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
preprocessor = { id = "com.replaymod.preprocess", version.ref = "preprocessor" }
preprocessorRoot = { id = "com.replaymod.preprocess-root", version.ref = "preprocessor" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }